name: CI

on:
  push:
    branches:
        - "main-127"

  # schedule:
  #   - cron: '15 14 * * *'
  workflow_dispatch:

env:
  # CONFL: ${{ secrets.CONFL }}
  DEBIAN_FRONTEND: noninteractive

jobs:
  build:

    defaults:
      run:
        shell: bash

    timeout-minutes: 180 # 3 hours
    
    strategy:

      fail-fast: false

      matrix:
        config:
          - prefix: "ubuntu-latest"
            method: 'a'
          - prefix: "windows-latest"
            method: 'a'
          - prefix: "ubuntu-latest"
            method: 'b'
          - prefix: "windows-latest"
            method: 'b'

    name: runner-${{ matrix.config.prefix }}
    
    runs-on: ${{ matrix.config.prefix }}

    steps:
      - uses: actions/setup-python@v4
        name: Setup python
        id: python
        with:
          python-version: "3.10"

      - uses: browser-actions/setup-chrome@v1
        name: Setup chrome
        id: setup-chrome
        with:
          chrome-version: 127

      - name: Checkout
        uses: actions/checkout@v2

      - name: Get chrome path
        run: |
          echo "${{ steps.setup-chrome.outputs.chrome-path }}" > chrome-path.txt
          echo "update chrome path to ${{ steps.setup-chrome.outputs.chrome-path }}"

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Run method A
        continue-on-error: true
        if: matrix.config.method == 'a'
        run: |
          python3 -X utf8 main-2.py -pc 20

      - name: Run method B
        continue-on-error: true
        if: matrix.config.method == 'b'
        run: |
          stopRunner="0"
          runAgain(){
             sleep 10800s
             echo '0' > loop.txt
             stopRunner="1"
          }
          runAgain &
          ReRunPy(){
            python3 -X utf8 main-2.py -pc 20 -tl 10
            if [[ "$stopRunner" == "0" ]];then
              ReRunPy
            fi
          }
          ReRunPy
